name: GKE Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: project-pallavi-tarke
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker authentication
      run: gcloud auth configure-docker

    - name: Build & push backend image
      run: |
        docker build -t gcr.io/project-pallavi-tarke/backend:latest -f docker/backend.Dockerfile .
        docker push gcr.io/project-pallavi-tarke/backend:latest

    - name: Build & push frontend image
      run: |
        docker build -t gcr.io/project-pallavi-tarke/frontend:latest -f docker/frontend.Dockerfile .
        docker push gcr.io/project-pallavi-tarke/frontend:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials multi-tier-gke --zone us-central1-c

    - name: Deploy backend and frontend
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend.yaml
